select [EPS]
      ,[ROA]
      ,[ROE]
      ,[S/N]
      ,[Banks]
      ,[Total Asset]
      ,[Total Capital]
      ,[Paid-up Capital]
      ,[Profit before tax]
      ,[Profit for the year]
      ,[Total Asset in 'USD']
      ,[Total Capital in 'USD']
      ,[Paid-up Capital in 'USD']
      ,[Profit before tax in 'USD']
      ,[Profit for the year in 'USD']
      ,[comprehensive income for year]
      ,[comprehensive income for year in 'USD']
from {{ source('bank_source', 'Banks 2023 2024') }}