select [EPS]
      ,[ROA]
      ,[ROE]
      ,[S/N]
      ,[Banks]
      ,[Net Income]
      ,[Total Asset]
      ,[Total Capital]
      ,[Paid-up Capital]
      ,[Profit before tax]
      ,[Net Income in 'USD']
      ,[Total Asset in 'USD']
      ,[Total Capital in 'USD']
      ,[Paid-up Capital in 'USD']
      ,[Profit for the year '000']
      ,[Profit before tax in 'USD']
      ,[Profit for the year in 'USD']
from {{ source('bank_source', 'Banks 2022 2023') }}