version: 2

sources:
    #sources from warehouse
  - name: etbanksfinancial
    description: "This is the source table for Banks and Insurances data"  
    tables:
      - name: Banks_2022_2023
        description: "This table contains data for banks for the years 2022 and 2023"    
      - name: Banks_2023_2024 
        description: "This table contains data for banks for the years 2023 and 2024"
      - name: Insurance_2022_2023
        description: "This table contains data for insurances for the years 2022 and 2023"
      - name: Insurance_2023_2024
        description: "This table contains data for insurances for the years 2023 and 2024"